<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.4 setup script
 * Date: Mon, 10 Dec 2012 22:35:29 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Mineshafter Squared Development Database [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Mineshafter Squared Development Database';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'ms2dev';
$cfg['Servers'][$i]['controlpass'] = 'ms2dev';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '50c6639d3867c1.63259348';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>